import type { BackendKind, HarnessCapabilities } from "./types"

export const DEFAULT_HARNESS_CAPABILITIES: Record<BackendKind, HarnessCapabilities> = {
  opencode: {
    sessions: true,
    prompt: true,
    abort: true,
    streaming: true,
    models: true,
    agents: true,
    todos: true,
    diff: true,
    filesystemBrowser: true,
    questions: true,
    permissions: true,
    commands: true,
    actions: false,
    sessionRename: true,
    sessionDelete: true,
    // Attachments reach the harness through the bridge; the OpenCode transport has no such path yet.
    attachments: false
  },
  omp: {
    sessions: true,
    prompt: true,
    abort: true,
    streaming: true,
    models: true,
    agents: false,
    todos: true,
    diff: false,
    filesystemBrowser: true,
    questions: false,
    permissions: false,
    commands: true,
    actions: true,
    sessionRename: true,
    sessionDelete: true,
    // Replaced by the live handshake as soon as /v1/capabilities answers.
    attachments: false
  },
  pi: {
    sessions: true,
    prompt: true,
    abort: true,
    streaming: true,
    models: true,
    agents: false,
    todos: false,
    diff: false,
    filesystemBrowser: true,
    questions: false,
    permissions: false,
    commands: true,
    actions: false,
    sessionRename: true,
    sessionDelete: true,
    attachments: false
  },
  claude: {
    sessions: true,
    prompt: true,
    abort: true,
    streaming: true,
    models: true,
    agents: false,
    todos: true,
    diff: false,
    filesystemBrowser: true,
    questions: false,
    permissions: false,
    commands: false,
    actions: false,
    sessionRename: true,
    sessionDelete: true,
    attachments: false
  },
  codex: {
    sessions: true,
    prompt: true,
    abort: true,
    streaming: true,
    models: true,
    agents: false,
    todos: true,
    diff: false,
    filesystemBrowser: true,
    questions: false,
    permissions: false,
    commands: true,
    actions: false,
    sessionRename: true,
    sessionDelete: true,
    attachments: false
  }
}
